README.md, UPGRADE.md, src/I18nBundle/Configuration/Configuration.php, src/I18nBundle/DependencyInjection/I18nExtension.php, src/I18nBundle/Migrations/Version00000001.php, src/I18nBundle/Migrations/Version20190224152059.php, src/I18nBundle/Resources/config/services/system.yml, src/I18nBundle/Tool/Install.php
=> Migration Installer

src/I18nBundle/EventListener/DetectorListener.php
=> check pimcore context on kernel response

.travis.yml, README.md
=> Prepare 2.4 Sealing

tests/_etc/travis/install
=> improve travis composer installation

README.md, UPGRADE.md, docs/52_PimcoreRedirects.md, src/I18nBundle/EventListener/ContextSwitchDetectorListener.php, src/I18nBundle/EventListener/DetectorListener.php, src/I18nBundle/EventListener/PimcoreRedirectListener.php, src/I18nBundle/Helper/DocumentHelper.php, src/I18nBundle/Helper/RequestValidatorHelper.php, src/I18nBundle/Manager/ZoneManager.php, src/I18nBundle/Resources/config/services/event.yml, src/I18nBundle/Resources/config/services/manager.yml, tests/_support/Helper/PimcoreBackend.php, tests/_support/Helper/PimcoreCore.php, tests/_support/Util/I18nHelper.php, tests/functional.zone.extended/PimcoreRedirectCest.php, tests/functional.zone.simple/PimcoreRedirectCest.php
=> Pimcore Redirect Modifier

README.md, UPGRADE.md, docs/52_PimcoreRedirects.md, src/I18nBundle/EventListener/ContextSwitchDetectorListener.php, src/I18nBundle/EventListener/DetectorListener.php, src/I18nBundle/EventListener/PimcoreRedirectListener.php, src/I18nBundle/Helper/DocumentHelper.php, src/I18nBundle/Helper/RequestValidatorHelper.php, src/I18nBundle/Manager/ZoneManager.php, src/I18nBundle/Resources/config/services/event.yml, src/I18nBundle/Resources/config/services/helper.yml, src/I18nBundle/Resources/config/services/manager.yml, tests/_support/Helper/PimcoreBackend.php, tests/_support/Util/I18nHelper.php, tests/functional.zone.extended/PimcoreRedirectCest.php, tests/functional.zone.simple/PimcoreRedirectCest.php
| Fixed tickets | #33
* implement pimcore redirect modifier, see #33
* split events, add redirect tests
* add some docs, fix phpstan
* add not found test
* improve host url test
=> Pimcore Redirect Modifier (cp from #34)

UPGRADE.md, docs/70_ContextSwitch.md, src/I18nBundle/EventListener/ContextSwitchDetectorListener.php, src/I18nBundle/Resources/config/services/event.yml, tests/_etc/config/bundle/symfony/config_full_page_cache.yml, tests/_support/Helper/Browser/PhpBrowser.php, tests/_support/Helper/PimcoreCore.php, tests/functional.full_page_cache.suite.dist.yml, tests/functional.full_page_cache/FullPageCacheCest.php, tests/functional.full_page_cache/_bootstrap.php
| Fixed tickets | #18 
* skip context switch check if fullpage cache is enabled
* update docs
* add full page cache test
* fix actor method names
=> Session fix (CP #37)

UPGRADE.md, docs/60_CodeExamples.md, src/I18nBundle/Exception/ContextNotDefinedException.php, src/I18nBundle/Manager/ContextManager.php, src/I18nBundle/Twig/Extension/I18nExtension.php, tests/_etc/bundle_configuration, tests/_etc/config/bundle/template/controller/DefaultController, tests/_etc/config/bundle/template/views/default, tests/_etc/config/bundle/template/views/languageSelector, tests/_support/Helper/PimcoreBackend.php, tests/functional.default/XliffExportCest.php
=> allow context failing

UPGRADE.md, docs/60_CodeExamples.md, src/I18nBundle/Exception/ContextNotDefinedException.php, src/I18nBundle/Manager/ContextManager.php, src/I18nBundle/Twig/Extension/I18nExtension.php, tests/_etc/bundle_configuration, tests/_etc/config/bundle/template/controller/DefaultController, tests/_etc/config/bundle/template/views/languageSelector, tests/_support/Helper/PimcoreBackend.php, tests/functional.default/XliffExportCest.php
| Fixed tickets | #28 
* allow context failing
* improve template locations
* add upgrade note
=> allow context failing (#39)

UPGRADE.md, src/I18nBundle/Adapter/Context/AbstractContext.php, src/I18nBundle/Adapter/Context/Country.php, src/I18nBundle/Adapter/Context/Language.php, src/I18nBundle/Adapter/PathGenerator/AbstractPathGenerator.php, src/I18nBundle/Adapter/PathGenerator/Document.php, src/I18nBundle/Adapter/Redirector/CookieRedirector.php, src/I18nBundle/Adapter/Redirector/FallbackRedirector.php, src/I18nBundle/Adapter/Redirector/GeoRedirector.php, src/I18nBundle/Adapter/Redirector/RedirectorBag.php, src/I18nBundle/DataCollector/I18nDataCollector.php, src/I18nBundle/Event/AlternateStaticRouteEvent.php, src/I18nBundle/Event/ContextSwitchEvent.php, src/I18nBundle/EventListener/Frontend/FrontPageMapperListener.php, src/I18nBundle/EventListener/Frontend/FrontendPathListener.php, src/I18nBundle/EventListener/Frontend/FrontendPathStaticRouteListener.php, src/I18nBundle/EventListener/Frontend/HeadLinkListener.php, src/I18nBundle/EventListener/Frontend/LinkPathListener.php, src/I18nBundle/Finder/PathFinder.php, src/I18nBundle/Twig/Extension/I18nExtension.php
=> Locale check

UPGRADE.md, src/I18nBundle/Adapter/Context/AbstractContext.php, src/I18nBundle/Adapter/Context/Country.php, src/I18nBundle/Adapter/Context/Language.php, src/I18nBundle/Adapter/PathGenerator/AbstractPathGenerator.php, src/I18nBundle/Adapter/PathGenerator/Document.php, src/I18nBundle/Adapter/Redirector/CookieRedirector.php, src/I18nBundle/Adapter/Redirector/FallbackRedirector.php, src/I18nBundle/Adapter/Redirector/GeoRedirector.php, src/I18nBundle/Adapter/Redirector/RedirectorBag.php, src/I18nBundle/DataCollector/I18nDataCollector.php, src/I18nBundle/Event/AlternateStaticRouteEvent.php, src/I18nBundle/Event/ContextSwitchEvent.php, src/I18nBundle/EventListener/Frontend/FrontPageMapperListener.php, src/I18nBundle/EventListener/Frontend/FrontendPathListener.php, src/I18nBundle/EventListener/Frontend/FrontendPathStaticRouteListener.php, src/I18nBundle/EventListener/Frontend/HeadLinkListener.php, src/I18nBundle/EventListener/Frontend/LinkPathListener.php, src/I18nBundle/Finder/PathFinder.php
| Fixed tickets | #41
* use locale instead of language iso, see #41
=> Locale check (#42)

UPGRADE.md, src/I18nBundle/Adapter/Context/AbstractContext.php, src/I18nBundle/Adapter/PathGenerator/Document.php, src/I18nBundle/Adapter/PathGenerator/StaticRoute.php
=> Link generator

UPGRADE.md, src/I18nBundle/Adapter/Context/AbstractContext.php, src/I18nBundle/Adapter/PathGenerator/Document.php, src/I18nBundle/Adapter/PathGenerator/StaticRoute.php
| Branch?       | dev-maste
| Fixed tickets | #15 
* respect link generator, resolves #15
* simplify generate link method
* add upgrade note
* phpstan fix
* ecs
=> Link generator (#43)

.travis.yml
=> update travis matrix for P6.2

.travis.yml, tests/_etc/travis/install, tests/functional.default.country/DisabledDocumentsCest.php, tests/functional.default.country/HrefLangCest.php, tests/functional.zone.extended/PimcoreRedirectCest.php, tests/functional.zone.extended/ZoneDocumentCest.php
=> pimcore 6.3 ready

.travis.yml, README.md, UPGRADE.md, composer.json, docs/10_GeoControl.md, src/I18nBundle/DependencyInjection/Configuration.php, src/I18nBundle/DependencyInjection/I18nExtension.php, src/I18nBundle/EventListener/ContextSwitchDetectorListener.php, src/I18nBundle/Helper/UserHelper.php, src/I18nBundle/Resources/config/services/helper.yml, tests/_bootstrap.php, tests/_etc/config/bundle/symfony/config_full_page_cache.yml, tests/_etc/config/bundle/system.yml.template, tests/_etc/travis/install, tests/_support/App/Pimcore/TestConfig.php, tests/_support/App/TestAppKernel.php, tests/_support/DependencyInjection/ServiceChangePass.php, tests/_support/Helper/PimcoreBackend.php, tests/_support/Helper/PimcoreCore.php, tests/functional.default.country.suite.dist.yml, tests/functional.default.suite.dist.yml, tests/functional.full_page_cache.suite.dist.yml, tests/functional.zone.extended.suite.dist.yml, tests/functional.zone.simple.suite.dist.yml, tests/unit.suite.dist.yml
=> Pimcore 6.5, PHP 7.4 matrix added

docs/26_Languages.md
| Fixed tickets | #54 
Follow-up of #54 to help others having the same problem. Please correct me if the doc change is not correct (does it make sense anywhere to set a language for a site document?).
=> [Docs] Sites should not have language

.travis.yml, README.md, UPGRADE.md, docs/28_StaticRoutes.md, docs/51_RedirectorAdapter.md, src/I18nBundle/Definitions.php, src/I18nBundle/DependencyInjection/Configuration.php, src/I18nBundle/EventListener/CanonicalListener.php, src/I18nBundle/EventListener/ContextSwitchDetectorListener.php, src/I18nBundle/EventListener/DetectorListener.php, src/I18nBundle/EventListener/Frontend/FrontPageMapperListener.php, src/I18nBundle/EventListener/Frontend/FrontendPathListener.php, src/I18nBundle/EventListener/Frontend/FrontendPathStaticRouteListener.php, src/I18nBundle/EventListener/Frontend/HeadLinkListener.php, src/I18nBundle/EventListener/Frontend/HeadMetaListener.php, src/I18nBundle/EventListener/Frontend/LinkPathListener.php, src/I18nBundle/EventListener/Frontend/ResponseExceptionListener.php, src/I18nBundle/EventListener/I18nStartupListener.php, src/I18nBundle/Helper/RequestValidatorHelper.php, src/I18nBundle/Manager/ZoneManager.php, src/I18nBundle/Resolver/PimcoreDocumentResolver.php, src/I18nBundle/Resolver/PimcoreDocumentResolverInterface.php, src/I18nBundle/Resources/config/services/event.yml, src/I18nBundle/Resources/config/services/resolver.yml
=> Pimcore 6.6 compatibility | Release 3.2.1

UPGRADE.md, src/I18nBundle/EventListener/Frontend/ResponseExceptionListener.php
=> Add Http Error Log on Exception Level

src/I18nBundle/Adapter/PathGenerator/Document.php
=> disable adding unavailable documents to zone tree

src/I18nBundle/Helper/UserHelper.php
=> Improve language redirects

src/I18nBundle/Adapter/PathGenerator/StaticRoute.php
| Deprecations? | yes
| Fixed tickets | -
=> fix if statement

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml
=> Fix mysql version for tests

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml
=> Workflow fixes

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml
=> Fix workflows branches

src/I18nBundle/Builder/ZoneSitesBuilder.php
fix realhosturl in ZoneSitesBuilder.php
=> fix realhosturl

src/I18nBundle/Context/I18nContext.php
fix linkedHref in getActiveLanguages()
=> fix linkedHref

README.md, docs/120_CookieSettings.md, src/I18nBundle/DependencyInjection/Configuration.php, src/I18nBundle/Helper/CookieHelper.php
| Branch?       | 3.x
| Fixed tickets | #88 
Hey! 👋
This PR adds the possibility to configure the cookie settings in the CookieHandler helper.
I've added the configuration as separate section instead of adding it to the cookie redirector because I didn't know if it will be used somewhere else in the future.
Thank you very much!
Best wishes
Tom
=> Cookie configuration (for 3.x branch)

UPGRADE.md, src/I18nBundle/Builder/RouteItemBuilder.php
=> Check against isFrontendRequestByAdmin in route item builder

UPGRADE.md
| Bug fix?      |no
| Deprecations? |no
=> add release notes

UPGRADE.md, src/I18nBundle/EventListener/Frontend/ResponseExceptionListener.php
| Branch?       | 4.0.6
| Fixed tickets | #107 
Fix missing site attribute in error page
=> Fix missing site attribute

UPGRADE.md, src/I18nBundle/Builder/RouteParameterBuilder.php, src/I18nBundle/Twig/Extension/I18nExtension.php
| Fixed tickets | -
Fixes #104 @pascalmoser ?
=> add site to request context, if available

src/I18nBundle/EventListener/Frontend/HeadLinkListener.php
| Branch?       | dev-master 
| Fixed tickets | #97
This fixes the alternate and default links being pushed via HTTP2.
=> Fix alternate links beeing pushed as web links

UPGRADE.md
=> prepare release

UPGRADE.md, docs/1_I18n.md, src/I18nBundle/EventListener/I18nPreviewListener.php, src/I18nBundle/EventListener/I18nStartupListener.php, src/I18nBundle/Helper/AdminLocaleHelper.php, src/I18nBundle/Helper/AdminMessageRendererHelper.php, src/I18nBundle/I18nEvents.php, src/I18nBundle/LinkGenerator/AbstractRequestAwareLinkGenerator.php, src/I18nBundle/PreviewGenerator/ObjectPreviewGenerator.php, src/I18nBundle/Resources/config/services/event.yml, src/I18nBundle/Resources/config/services/generator.yml, src/I18nBundle/Resources/config/services/helper.yml, src/I18nBundle/Resources/install/translations/admin.csv, src/I18nBundle/Resources/views/preview_incomplete_message.html.twig
=> introduce object preview generator, fix link generation from editables

UPGRADE.md, src/I18nBundle/Builder/RouteItemBuilder.php, src/I18nBundle/Builder/ZoneSitesBuilder.php, src/I18nBundle/EventListener/Frontend/HeadLinkListener.php, src/I18nBundle/Helper/RequestValidatorHelper.php, src/I18nBundle/Manager/I18nContextManager.php, src/I18nBundle/Model/RouteItem/BaseRouteItem.php, src/I18nBundle/Model/RouteItem/BaseRouteItemInterface.php, src/I18nBundle/Modifier/RouteModifier.php, src/I18nBundle/PreviewGenerator/ObjectPreviewGenerator.php
=> Improve FrontendRequestByAdmin determination

src/I18nBundle/LinkGenerator/AbstractRequestAwareLinkGenerator.php
| Fixed tickets | #122 
See #122
=> #122 Use symfony attributes for required members

UPGRADE.md, src/I18nBundle/LinkGenerator/AbstractRequestAwareLinkGenerator.php, src/I18nBundle/PreviewGenerator/ObjectPreviewGenerator.php
- Use correct Site ID in object preview generator
- Suppress Link Generation Exception in Admin Mode
=> Object Preview Improvements

UPGRADE.md, src/I18nBundle/LinkGenerator/AbstractRequestAwareLinkGenerator.php, src/I18nBundle/Resources/config/services/route.yml
| Fixed tickets | #126 (follow-up)
=> suppress zone exception in frontend admin request

src/I18nBundle/Resources/config/services/route.yml
=> mark RouteModifier service as lazy

UPGRADE.md
=> add upgrade notes

UPGRADE.md, src/I18nBundle/EventListener/AdminSiteListener.php, src/I18nBundle/Modifier/RouteItem/Type/RequestAwareModifier.php
=> resolve site and locale in areabrick-render-index-editmod route

UPGRADE.md, src/I18nBundle/EventListener/Frontend/ResponseExceptionListener.php
| Branch?       | dev-master for features / 2.4 for bug fixes
| New feature?  |no
| Fixed tickets |-
Allows http error logging in the pimcore backend
=> Writing http errors to DB analogue to pimcore

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml, :q, README.md
=> Pimcore 10.6 release

:q, ISSUE_TEMPLATE.md, UPGRADE.md, src/I18nBundle/EventListener/I18nPreviewListener.php
| Branch?       | 4.x
| Fixed tickets | #...
=> Move preview listener to earlier state

UPGRADE.md, docs/20_Zones.md, docs/50_CustomLocaleAdapter.md, docs/60_CodeExamples.md, docs/91_StaticRoutes.md, src/Adapter/PathGenerator/Document.php, src/Adapter/Redirector/GeoRedirector.php, src/Builder/ZoneBuilder.php, src/Builder/ZoneSitesBuilder.php, src/Context/I18nContext.php, src/DataCollector/I18nDataCollector.php, src/DependencyInjection/Configuration.php, src/EventListener/Frontend/HeadLinkListener.php, src/EventListener/Frontend/HeadMetaListener.php, src/Model/Zone.php, src/Model/ZoneInterface.php, tests/FunctionalDefaultCountry/CountryRedirectorCest.php, tests/Unit/Config/ConfigurationTest.php, tests/_etc/config/bundle/config_default.yaml, tests/_etc/config/bundle/config_default_country.yaml, tests/_etc/config/bundle/config_full_page_cache.yaml, tests/_etc/config/bundle/config_zone_extended.yaml, tests/_etc/config/bundle/config_zone_hosts.yaml, tests/_etc/config/bundle/config_zone_simple.yaml
| BC breaks?    | yes
This PR removes the 'mode` flag to simplify logic.
=> remove i18n mode

UPGRADE.md, config/pimcore/config.yaml, config/services/helper.yaml, docs/51_RedirectorAdapter.md, src/Adapter/Redirector/AbstractRedirector.php, src/Adapter/Redirector/CookieRedirector.php, src/Adapter/Redirector/GeoRedirector.php, src/Adapter/Redirector/RedirectorInterface.php, src/DependencyInjection/Compiler/RedirectorAdapterPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/I18nExtension.php, src/EventListener/DetectorListener.php, src/Helper/CookieHelper.php
| Fixed tickets | #140
This PR provides an additional `config` option for redirector adapters, enabling a more flexible use of these.
=> configurable redirector adapter

UPGRADE.md, src/Adapter/Redirector/AbstractRedirector.php, src/Adapter/Redirector/RedirectorInterface.php, src/DependencyInjection/Compiler/RedirectorAdapterPass.php, src/EventListener/DetectorListener.php, src/Registry/RedirectorRegistry.php, templates/profiler/data_collector.html.twig
=> fix redirector state check

UPGRADE.md, src/Modifier/RouteModifier.php
| Deprecations? |no
| Fixed tickets | #
fixes replacement of locale segment in url, if there is no locale mapping
=> fix locale url mapping if empty

UPGRADE.md, src/I18nBundle/Modifier/RouteItem/Type/PimcoreExportDataAwareModifier.php, src/I18nBundle/Resources/config/services/route.yml
=> add locale and site automatically in export mode

UPGRADE.md, config/services/event.yaml
=> decorate response exception listener properly

UPGRADE.md, src/I18nBundle/Modifier/RouteItem/Type/PimcoreExportDataAwareModifier.php, src/I18nBundle/Modifier/RouteItem/Type/PimcoreInlineRendererAwareModifier.php, src/I18nBundle/Resources/config/services/route.yml
=> Add document modifier

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml, UPGRADE.md, src/Manager/I18nContextManager.php, tests/_envs/github.yml
=> prevent applying str_contains on null value

docs/100_LocalizeDocuments.md, docs/26_Languages.md
Links to Pimcore 5.x docs are not available anymore.
=> Fix links to Pimcore docs

README.md, src/Routing/I18nRouter.php, tests/Support/Helper/I18n.php
* Fix PHPstan tests
* Update readme
=> Update README maintenance info and fix method call in I18nRouter
